package com.citi.system.entities;

import com.citi.system.dto.User;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class CapWiseStockSymbols {

	String[] small_cap = new String[] {"ALOKINDS.NS","AMARAJABAT.NS","AMBER.NS","ANGELONE.NS","ANURAS.NS","BAJAJELEC.NS","BALAMINES.NS","MAHABANK.NS","BIRLACORPN.NS","BSOFT.NS",
			"CESC.NS","CANFINHOME.NS","CENTRALBK.NS","CDSL.NS","CHAMBLFERT.NS","CHEMPLASTS.NS","CAMS.NS","CYIENT.NS","DEVYANI.NS","DBL.NS","FSL.NS","GRANULES.NS","GRAPHITE.NS",
			"HEG.NS","HFCL.NS","HINDCOPPER.NS","IDFC.NS","IBULHSGFIN.NS","IOB.NS","INDIGOPNTS.NS","INTELLECT.NS","JBCHEPHARM.NS","JUBLINGREA.NS","KPITTECH.NS","LATENTVIEW.NS",
			"LXCHEM.NS","MEDPLUS.NS","METROBRAND.NS","MCX.NS","NBCC.NS","PNBHOUSING.NS","PVR.NS","POONAWALLA.NS","RBLBANK.NS","RADICO.NS","ROUTE.NS","STLTECH.NS","UTIAMC.NS","WELSPUNIND.NS","ZENSARTECH.NS"};
	
	String[] mid_cap = new String[] {"ABB.NS","AUBANK.NS","AARTIIND.NS","ABBOTINDIA.NS","ALKEM.NS","ASHOKLEY.NS","ASTRAL.NS","AUROPHARMA.NS","BALKRISIND.NS","BATAINDIA.NS","BEL.NS","BHARATFORG.NS",
			"BHEL.NS","CANBK.NS","COFORGE.NS","CONCOR.NS","CUMMINSIND.NS","ESCORTS.NS","FEDERALBNK.NS","GODREJPROP.NS","GUJGASLTD.NS","HAL.NS","HINDPETRO.NS","IDFCFIRSTB.NS","IRCTC.NS",
			"JINDALSTEL.NS","L&TFH.NS","LTTS.NS","LICHSGFIN.NS","MRF.NS","M&MFIN.NS","MFSL.NS","MPHASIS.NS","OFSS.NS","PAGEIND.NS","PETRONET.NS","PFC.NS","RECLTD.NS","SRTRANSFIN.NS","SUNTV.NS","TVSMOTOR.NS",
			"TATACOMM.NS","TATAPOWER.NS","RAMCOCEM.NS","TORNTPOWER.NS","TRENT.NS","UBL.NS","IDEA.NS","VOLTAS.NS","ZEEL.NS"};
	
	String[] large_cap = new String[] {"ACC.NS","ADANIENT.NS","ADANIGREEN.NS","ADANITRANS.NS","AMBUJACEM.NS","DMART.NS","BAJAJHLDNG.NS","BANDHANBNK.NS","BANKBARODA.NS","BERGEPAINT.NS","BIOCON.NS","BOSCHLTD.NS",
			"CHOLAFIN.NS","COLPAL.NS","DLF.NS","DABUR.NS","NYKAA.NS","GAIL.NS","GLAND.NS","GODREJCP.NS","HDFCAMC.NS","HAVELLS.NS","ICICIGI.NS","ICICIPRULI.NS","IOC.NS","INDUSTOWER.NS","NAUKRI.NS","INDIGO.NS",
			"JUBLFOOD.NS","LTI.NS","LUPIN.NS","MARICO.NS","MINDTREE.NS","MUTHOOTFIN.NS","NMDC.NS","PAYTM.NS","PIIND.NS","PIDILITIND.NS","PEL.NS","PGHH.NS","PNB.NS","SBICARD.NS","SRF.NS","SIEMENS.NS",
			"SAIL.NS","TORNTPHARM.NS","MCDOWELL-N.NS","VEDL.NS","ZOMATO.NS","ZYDUSLIFE.NS"};
	
	
}
